name: vint
on: [push, pull_request]
jobs:
  vint:
    name: vim lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: vint-reviewdog
        uses: reviewdog/action-vint@v1.0.1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: vint
        env:
          DEFAULT_BRANCH: master
