name: vint
on: [push, pull_request]
jobs:
  vint:
    name: vim lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout
      - name: vint-reviewdog
        uses: reviewdog/action-vint
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.github_token }}
